name: Deploy on commit?

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Upgrade to v3 for Node.js 16 and 20 support

    - name: Install Node.js
      uses: actions/setup-node@v3  # Upgrade to v3 for Node.js 16 and 20 support
      with:
        node-version: '20'  # Use the latest version (or '16' if your project needs it)

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub
